Repository Ni3verma/Safe-Box, pull requests merged in 2021-07, with the labels that each got.

#25 fixed git command
  CONTRIBUTING.md
  README.md
Labels: bug fix

#20 Displaying all user data in home screen
  .idea/misc.xml
  app/src/main/java/com/andryoga/safebox/data/db/dao/LoginDataDao.kt
  app/src/main/java/com/andryoga/safebox/data/db/docs/SearchLoginData.kt
  app/src/main/java/com/andryoga/safebox/data/db/secureDao/LoginDataDaoSecure.kt
  app/src/main/java/com/andryoga/safebox/data/repository/LoginDataRepositoryImpl.kt
  app/src/main/java/com/andryoga/safebox/data/repository/interfaces/LoginDataRepository.kt
  app/src/main/java/com/andryoga/safebox/di/RepositoryModule.kt
  app/src/main/java/com/andryoga/safebox/ui/common/BindingUtils.kt
  app/src/main/java/com/andryoga/safebox/ui/common/Utils.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/child/all/AllInfoFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/child/all/AllInfoViewModel.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/child/common/UserDataAdapter.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/child/common/UserDataAdapterEntity.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/child/common/UserDataDiffCallback.kt
  app/src/main/res/drawable/empty.xml
  app/src/main/res/drawable/no_result.png
  app/src/main/res/layout/all_info_fragment.xml
  app/src/main/res/layout/row_home_info_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#30 Redesigned add new data option UI
  app/src/main/java/com/andryoga/safebox/common/Constants.kt
  app/src/main/java/com/andryoga/safebox/ui/common/Utils.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/HomeFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/HomeViewModel.kt
  app/src/main/res/layout/add_new_user_personal_data.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/add_new_user_personal_data_xml_constraintlayout_scene.xml
Labels: UI, enhancement

#31 modified git templates
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/pull_request_template.md
Labels: enhancement

#37 Added app icon
  .idea/misc.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: UI, enhancement

#24 Added feature of adding new bank account data
  app/src/main/java/com/andryoga/safebox/data/db/SafeBoxDatabase.kt
  app/src/main/java/com/andryoga/safebox/data/db/dao/BankAccountDataDao.kt
  app/src/main/java/com/andryoga/safebox/data/db/entity/BankAccountDataEntity.kt
  app/src/main/java/com/andryoga/safebox/data/db/secureDao/BankAccountDataDaoSecure.kt
  app/src/main/java/com/andryoga/safebox/data/repository/BankAccountDataRepositoryImpl.kt
  app/src/main/java/com/andryoga/safebox/data/repository/interfaces/BankAccountDataRepository.kt
  app/src/main/java/com/andryoga/safebox/di/CacheModule.kt
  app/src/main/java/com/andryoga/safebox/di/RepositoryModule.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/HomeFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/addNewData/bankAccount/AddNewBankAccountDataDialogFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/addNewData/bankAccount/AddNewBankAccountDataViewModel.kt
  app/src/main/java/com/andryoga/safebox/ui/view/home/addNewData/bankAccount/AddNewBankAccountScreenData.kt
  app/src/main/res/layout/fragment_add_new_bank_account_data_dialog.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 fixed spacing issue in add new login data screen
  app/src/main/res/layout/dialog_add_new_login_data.xml
Labels: UI, bug fix

#18 Hint functionality for user password
  app/src/main/java/com/andryoga/safebox/data/db/dao/UserDetailsDao.kt
  app/src/main/java/com/andryoga/safebox/data/db/entity/UserDetailsEntity.kt
  app/src/main/java/com/andryoga/safebox/data/db/secureDao/UserDetailsDaoSecure.kt
  app/src/main/java/com/andryoga/safebox/data/repository/UserDetailsRepositoryImpl.kt
  app/src/main/java/com/andryoga/safebox/data/repository/interfaces/UserDetailsRepository.kt
  app/src/main/java/com/andryoga/safebox/ui/common/Utils.kt
  app/src/main/java/com/andryoga/safebox/ui/view/chooseMasterPswrd/ChooseMasterPswrdFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/chooseMasterPswrd/ChooseMasterPswrdValidationFailureCode.kt
  app/src/main/java/com/andryoga/safebox/ui/view/chooseMasterPswrd/ChooseMasterPswrdViewModel.kt
  app/src/main/java/com/andryoga/safebox/ui/view/login/LoginFragment.kt
  app/src/main/java/com/andryoga/safebox/ui/view/login/LoginViewModel.kt
  app/src/main/res/layout/choose_master_pswrd_fragment.xml
  app/src/main/res/layout/login_fragment.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
